version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql.railway.internal:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: iZpdsssFymunCtRULTLkmzKQxFKnnOBZ
      WORDPRESS_DB_NAME: railway
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: iZpdsssFymunCtRULTLkmzKQxFKnnOBZ
